# Generated by Django 4.2.3 on 2024-09-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor_total', models.FloatField()),
                ('cliente', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
    ]
