# Generated by Django 4.2.3 on 2024-09-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_item_remove_pedido_descricao_pedido_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
